######################################################################
##
## Filename: initTest.udo
## Created on: Sat Jan 09 11:46:26 PM Iran Standard Time 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
