tclcmd = { ...
'vsimmatlabsysobj main -voptargs="+acc" -t 1ps -L xilinxcorelib_ver -L unisims_ver -L unimacro_ver -L secureip -lib work glbl;', ...
'add wave main/*;', ...
};
vsim('tclstart',tclcmd,'vsimdir','C:\modeltech64_10.5\win64')
